### ISSUE TITLE
identify the snippet that could not be rendered

### ISSUE THREAD

**Issue by tkimnguyen** [castlecms/castle.cms#122]
instead of just having "We apologize, there was an error rendering this snippet"

**Comment by tkimnguyen** [comment]
I had that appear twice when viewing the @@dashboard on a plain Castle site on which I'd customized and cleaned out the front-page and put new tiles there. When I log in, I'm taken to the dashboard automatically. 

![screen shot 2018-01-03 at 11 31 04 pm](https://user-images.githubusercontent.com/815418/34551304-2f7a8ca2-f0de-11e7-8bef-5a1172f1d8ac.jpg)

**Comment by tkimnguyen** [comment]
I checked the log file and found this error, but it does not appear in /prefs_error_log_form even if you comment out or remove the "Unauthorized" exception type from the ignored list:

```
2018-01-05T00:14:29 ERROR castle.cms Error rendering tile on context: /Castle, data: {u'fragment': 'dashboard-statistic\
s', u'X-Tile-Persistent': 'yes'},
Traceback (most recent call last):
  File "/home/kim/src/castle.cms/castle/cms/tiles/base.py", line 118, in __call__
    res = self.render()
  File "/home/kim/src/castle.cms/castle/cms/tiles/fragment.py", line 20, in render
    return fragment(options=options)
  File "/home/kim/src/castle.cms/castle/cms/fragments/__init__.py", line 274, in __call__
    return zpt._exec(boundNames, args, kwargs)
  File "/home/kim/src/castle.cms/eggs/Zope2-2.13.26-py2.7.egg/Products/PageTemplates/ZopePageTemplate.py", line 338, in\
 _exec
    result = self.pt_render(extra_context=bound_names)
  File "/home/kim/src/castle.cms/eggs/Zope2-2.13.26-py2.7.egg/Products/PageTemplates/ZopePageTemplate.py", line 435, in\
 pt_render
    result = PageTemplate.pt_render(self, source, extra_context)
  File "/home/kim/src/castle.cms/eggs/Zope2-2.13.26-py2.7.egg/Products/PageTemplates/PageTemplate.py", line 87, in pt_r\
ender
    showtal=showtal)
  File "/home/kim/src/castle.cms/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, i\
n pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/kim/src/castle.cms/eggs/five.pt-2.2.4-py2.7.egg/five/pt/engine.py", line 98, in __call__
    return self.template.render(**kwargs)
  File "/home/kim/src/castle.cms/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/kim/src/castle.cms/eggs/Chameleon-2.25-py2.7.egg/chameleon/zpt/template.py", line 261, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/kim/src/castle.cms/eggs/Chameleon-2.25-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/kim/src/castle.cms/eggs/Chameleon-2.25-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "6576591ab1af1c748e4348f74ec76b81.py", line 128, in render
  File "/home/kim/src/castle.cms/eggs/five.pt-2.2.4-py2.7.egg/five/pt/expressions.py", line 135, in __call__
    base = self.traverse(base, request, path_items)
  File "/home/kim/src/castle.cms/eggs/five.pt-2.2.4-py2.7.egg/five/pt/expressions.py", line 123, in traverse
    base = traverser(name)
  File "/home/kim/src/castle.cms/eggs/Zope2-2.13.26-py2.7.egg/OFS/Traversable.py", line 317, in restrictedTraverse
    return self.unrestrictedTraverse(path, default, restricted=True)
  File "/home/kim/src/castle.cms/eggs/Zope2-2.13.26-py2.7.egg/OFS/Traversable.py", line 205, in unrestrictedTraverse
    obj, obj, name, next):
Unauthorized: You are not allowed to access '@@dashboard-utils' in this context

 - Expression: "context/@@dashboard-utils"
 - Filename:   dashboard-statistics
 - Location:   (line 1: col 24)
 - Arguments:  repeat: {...} (0)
               template: <ImplicitAcquisitionWrapper dashboard-statistics at 0x7f7535100be0>
               request: <instance - at 0x7f753436e200>
               utils: <Utils castle-utils at 0x7f752b419450>
               public_url: https://bobat30.com
               here: <ImplicitAcquisitionWrapper Castle at 0x7f753551a4b0>
               portal: <ImplicitAcquisitionWrapper Castle at 0x7f753551a4b0>
               registry: <ImplicitAcquisitionWrapper portal_registry at 0x7f75366c8a00>
	       nothing: <NoneType - at 0x8fd4d0>
               target_language: <NoneType - at 0x8fd4d0>
               translate: <function translate at 0x7f752b570c80>
               container: <ImplicitAcquisitionWrapper Castle at 0x7f753551a4b0>
               modules: <instance - at 0x7f753e52c050>
               wrapped_repeat: <SafeMapping - at 0x7f752aecfaf8>
               portal_url: https://bobat30.com
               site_url: https://bobat30.com
               default: <object - at 0x7f7545f6c550>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper Castle at 0x7f753551a4b0>
               tile: <FragmentTile castle.cms.fragment at 0x7f752b419ad0>
               view: <FragmentView dashboard-statistics at 0x7f752b592210>
               root: <ImplicitAcquisitionWrapper Zope at 0x7f7535fadc30>
               options: {...} (1)
               user: <ImplicitAcquisitionWrapper - at 0x7f75365a4550>

**Comment by tkimnguyen** [comment]
The code that outputs that generic error message is at https://github.com/castlecms/castle.cms/blob/4992959bd189b8836fd82be3ba4e6010c8ec62a9/castle/cms/tiles/base.py#L145 which is maybe ok for regular users but doesn't give enough info to track down the problem. For users who have Site Administrator or Manager role, maybe we could output something more, or at least include a link to /prefs_error_form assuming there is a way to ensure that the error is logged there.

**Comment by vangheem** [comment]
We're doing some issue reaping and closing out inactive issues. Most current project management/bug tracking is being done internally at Wildcard Corp. This tracker will remain open for the public to submit and track issues.

If this bug/feature is still relevant and being worked on/needs fixing, please feel free to reopen.
